# Generated by Django 5.1 on 2024-08-31 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='recvTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
